# This extend our general Ruff rules specifically for the examples
extend = "../pyproject.toml"

lint.extend-ignore = [
  "T201", # Allow the use of print() in examples
  "S106", # We have an demo token in the example
]
